// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovrizbbcgpwxskoaowrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92cml6YmJjZ3B3eHNrb2Fvd3JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDIwNzUsImV4cCI6MjA2OTI3ODA3NX0.OWr1-JmXphVUtuQ_eSOth-EalRvxrnaX6gzXIgKjR38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});